### ISSUE TITLE
Global Platform Access Control implementation is not complete.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [seek-for-android/pool#34]
```
What's the problem?

The Global Platform Access Control specification is not completely implemented 
as called for on page 17, where the specifications states: If the ARA-M is not 
present, the Access Control enforcer shall retrieve the access rules from the 
Access Rule Files (ARF), as illustrated in Figure 2-4.


What steps will reproduce the problem?
1. Configure UICC with access control rules in ARF, but no ARA-M is present
2.
3.

What is the expected output? What do you see instead?

The rules in the ARF should be followed; however, with the current 
implementation all access will be denied.

What version of the product are you using? On what operating system?
N/A

Please provide any additional information below.
```

Original issue reported on code.google.com by `EricHil...@gmail.com` on 27 Aug 2012 at 9:11

**Comment by angelsephirot** [comment]
There is no support of ARA-M applet official  AID in the code.

**Comment by marcobrador** [comment]
Hi,

What do you mean? I am sorry but I don't get your comment.

Regards,
Marc

**Comment by angelsephirot** [comment]
When we look at the global platform spec, here is the AID that should be used for the ARA-M applet:
A00000015141434C00 (cf GPD_SE_Access_Control_v1.0.pdf chapter 7.1.3)
So SEEK do not used this AID but this one in the class PKCS15Handler.java 
here are the AID used in SEEK:   GPAC_ARF_AID = A000000018475041432D3135
 and the second one for the PKCS15 file PKCS15_AID =A000000063504B43532D3135 this last one is offically supported from GP specification (cf GPD_SE_Access_Control_v1.0.pdf chapter 7.1.3)

In order to support ARA-M applet seek must used first the offical AID define by the global platform specification and used in the official Android master code starting from version 5.0.1

Sincelery;
Charles

**Comment by marcobrador** [comment]
Please, see line 52 of https://github.com/seek-for-android/platform_packages_apps_SmartCardService/blob/android-5.0.0_r3-scapi/src/org/simalliance/openmobileapi/service/security/ara/AraController.java

This is the source code that corresponds to the latest version of SEEK, v4.0.0.

**Comment by angelsephirot** [comment]
Ok thank you, i have misread.
So I can post the issue in Google code because the master code don't support the fallback to the ARF as specified in GP.

**Comment by marcobrador** [comment]
The code supports both ARA and ARF and is compliant with GP SEAC 1.0:
https://github.com/seek-for-android/platform_packages_apps_SmartCardService/tree/android-5.0.0_r3-scapi/src/org/simalliance/openmobileapi/service/security

**Comment by angelsephirot** [comment]
Yes I know, but it is not he case in the Android Master Code:
following this statement
https://source.android.com/devices/tech/config/uicc.html
and looking at 
https://android.googlesource.com/platform/frameworks/opt/telephony/+/master/src/java/com/android/internal/telephony/uicc/UiccCarrierPrivilegeRules.java
