### ISSUE TITLE
Vulnerability in add-on terminal loading for versions 3.1.0 and below

### ISSUE THREAD

**Issue by michaelroland** [seek-for-android/pool#90]
We found a vulnerability in the code that loads add-on terminals (on versions prior to 4.0.0) that allows arbitrary code coming from a specially crafted Android application package (APK) to be injected into and executed by the smartcard system service component. This can be exploited to gain elevated capabilities, such as privileges protected by signature- and system-level permissions assigned to this
service and normally not available to third-party apps.

Add-on terminals are classes loaded and instantiated from third party application packages into the execution context of the smartcard service (`packageName` is the third party APK package containing the add-on terminal, `className` is the class implementing the add-on terminal):

```java
Context pkgContext = context.createPackageContext(packageName, Context.CONTEXT_IGNORE_SECURITY | Context.CONTEXT_INCLUDE_CODE);
ClassLoader classLoader = pkgContext.getClassLoader ();
Class cls = classLoader.loadClass(className);
mInstance = cls.getConstructor(Context.class).newInstance(context);
```

The smartcard service performs this loading without doing any security checks (e.g. if the third party package can be trusted in any way). Hence, any code that is implemented in the constructor of the add-on terminal class will be automatically executed in the context of the service.

- A detailed report on this issue is available here: [*Executing Arbitrary Code in the Context of the Smartcard System Service*, arXiv:1601.05833 [cs.CR]](http://arxiv.org/abs/1601.05833)
- Example exploit code to reproduce the issue is available on GitHub: https://github.com/michaelroland/omapi-cve-2015-6606-exploit
- Patch for SEEK 3.1.0 to temporarily disable the vulnerability by completely disabling add-on terminals: https://usmile.at/sites/default/files/blog/seek_3_1_0_CVE-2015-6606.patch
- Patch for SEEK 3.0.0 to temporarily disable the vulnerability by completely disabling add-on terminals: https://usmile.at/sites/default/files/blog/seek_3_0_0_CVE-2015-6606.patch

**This issue has been assigned CVE-2015-6606 and was initially announced in the [October 2015 Nexus Security Bulletin](http://source.android.com/security/bulletin/2015-10-01.html).**

**Comment by marcobrador** [comment]
Hi Michael,

Many thanks for your detailed report.

The SEEK for Android team is very happy to see people investigating these topics and helping the project evolve, mature and get better over time. Your contributions and feedback were very helpful in fixing this security issue and we would like to encourage everyone to contribute in similar ways so we can together improve SEEK. Again, many thanks to you Michael and to all the team in the University of Applied Sciences Upper Austria who contributed in the research.

We are also happy to announce that the reported vulnerability was fixed in Smartcard Service 4.0.0, released in July 2015.

Best regards,
Marc Obrador & the SEEK for Android team
